# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-02 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_text', models.CharField(max_length=400)),
                ('post_date', models.DateField()),
            ],
        ),
    ]
